struct TMissile {
    __cls* cls;

    PTR graph;
    int index;
    byte kind; // 50 - rocket, 61 - torpedo
    byte tech_level;
    byte max_dmg;
    byte min_dmg;
    _pair_float pos;
    float direction;
    float speed;
    TStar* star;
    TShip* owner;
    PTR target;
    _gap _2C;
    _gap _2D;
    _gap _2E;
    _gap _2F;
    _gap _30;
    _gap _31;
    _gap _32;
    _gap _33;
    _gap _34;
    _gap _35;
    _gap _36;
    _gap _37;
    _gap _38;
    _gap _39;
    _gap _3A;
    _gap _3B;
    _gap _3C;
    _gap _3D;
    _gap _3E;
    _gap _3F;
    _gap _40;
    _gap _41;
    _gap _42;
    _gap _43;
    _gap _44;
    _gap _45;
    _gap _46;
    _gap _47;
    _gap _48;
    _gap _49;
    _gap _4A;
    _gap _4B;
    _gap _4C;
    _gap _4D;
    _gap _4E;
    _gap _4F;
    _gap _50;
    _gap _51;
    _gap _52;
    _gap _53;
    _gap _54;
    _gap _55;
    _gap _56;
    _gap _57;
    _gap _58;
    _gap _59;
    _gap _5A;
    _gap _5B;
    _gap _5C;
    _gap _5D;
    _gap _5E;
    _gap _5F;
    _gap _60;
    _gap _61;
    _gap _62;
    _gap _63;
    _gap _64;
    _gap _65;
    _gap _66;
    _gap _67;
    _gap _68;
    _gap _69;
    _gap _6A;
    _gap _6B;
    _gap _6C;
    _gap _6D;
    _gap _6E;
    _gap _6F;
    _gap _70;
    _gap _71;
    _gap _72;
    _gap _73;
};

struct TCustomMissile {
    TMissile;

    _gap _74;
    _gap _75;
    _gap _76;
    _gap _77;
};