/*
   This file has been generated by IDA.
   It contains local type definitions from
   the type library 'rangers'
*/

#define __int8 char
#define __int16 short
#define __int32 int
#define __int64 long long

struct THashEC;

/* 240 */
struct TList
{
  void *cls;
  int *data_p;
  int count;
  int capacity;
};

/* 241 */
struct TStack
{
  void *cls;
  TList *list;
};

/* 252 */
enum TVarEC_type
{
  TVarEC_type_unknown = 0x0,
  TVarEC_type_int = 0x1,
  TVarEC_type_dword = 0x2,
  TVarEC_type_float = 0x3,
  TVarEC_type_str = 0x4,
  TVarEC_type_externfun = 0x5,
  TVarEC_type_6 = 0x6,
  TVarEC_type_fun = 0x7,
  TVarEC_type_8 = 0x8,
  TVarEC_type_array = 0x9,
  TVarEC_type_ref = 0xA,
};

/* 242 */
struct TVarEC
{
  void *cls;
  void *name;
  TVarEC_type type;
  int val_int;
  unsigned int val_dword;
  _BYTE gap14[4];
  double val_float;
  int val_str;
  void *val_externfun;
  _BYTE gap28[4];
  void *val_fun;
  void *val_class;
  void *val_array;
  TVarEC *val_ref;
};

/* 243 */
struct TBufEC
{
  int cls;
  int count;
  int capacity;
  int ptr;
  byte *data_p;
};

/* 244 */
struct TFileEC
{
  int cls;
  int field_4;
  int is_opened;
  int filename;
  int field_10;
  int field_14;
  int field_18;
};

/* 245 */
struct TPackCollectionEC
{
  int cls;
  TPackCollectionEC *field_4;
  TPackCollectionEC *field_8;
  THashEC *field_C;
  int field_10;
  int field_14;
  int field_18;
  int field_1C;
};

/* 246 */
struct THashEC
{
};

/* 247 */
struct TPackFileEC
{
};

/* 248 */
struct TBlockParEC
{
};

/* 249 */
struct TMessagePlayer
{
  int field_0;
  int field_4;
  int field_8;
  int field_C;
  int field_10;
  int field_14;
  int field_18;
  int field_1C;
  int field_20;
  int field_24;
  int field_28;
  int field_2C;
  int field_30;
  int field_34;
  int field_38;
  int field_3C;
};

/* 250 */
struct TDemo
{
  void *cls;
  TBufEC *buf_p;
};

/* 251 */
struct TVarArrayEC
{
  int field_0;
  int field_4;
  int field_8;
  int field_C;
  int field_10;
  int field_14;
  int field_18;
  int field_1C;
  int field_20;
  int field_24;
  int field_28;
  int field_2C;
};

/* 253 */
struct TCodeAnalyzerEC
{
  int field_0;
  TCodeAnalyzerEC *field_4;
  TCodeAnalyzerEC *field_8;
  int field_C;
  int field_10;
  int field_14;
  int field_18;
  int field_1C;
  int field_20;
};

/* 254 */
struct TExpressionEC
{
};

/* 255 */
struct TItem
{
};

/* 256 */
struct TShip
{
};

/* 257 */
struct __TCls
{
};

